Repository umoqnier/cl-2024-2-lab, pull requests merged in 2024-05, with the labels that each got.

#34 Practica04
  practices/Super-Gabriel/README.md
  practices/Super-Gabriel/practica04.py
Labels: delay-1

#35 practica4 terminada
  practices/CervantesAlexis/practica4/practica4.py
Labels: delay-1

#27 Practica3/zipf
  practices/CervantesAlexis/practica03/practica3.py
Labels: on-time

#45 Práctica 4 - Tokenización
  practices/jardondiego/pr4/axolotl_n_plain.txt
  practices/jardondiego/pr4/axolotl_plain.txt
  practices/jardondiego/pr4/axolotl_plain_test.txt
  practices/jardondiego/pr4/brown_plain.txt
  practices/jardondiego/pr4/brown_plain_test.txt
  practices/jardondiego/pr4/tokenization.ipynb
  practices/jardondiego/pr4/tokenization.py
Labels: delay-2

#38 P5: word2vec
  practices/MaiteDT/practica05/palabrasavectores.py
Labels: on-time

#42 Add P05 files
  practices/Ramon-OC/practica05/P05.py
Labels: delay-1

#46 Práctica 7 - Traducción
  notebooks/7_Neural_machine_translation.ipynb
  practices/jardondiego/pr7/dev.es
  practices/jardondiego/pr7/dev.nah
  practices/jardondiego/pr7/pr7_translation.ipynb
  practices/jardondiego/pr7/test.es
  practices/jardondiego/pr7/train.es
  practices/jardondiego/pr7/train.nah
Labels: delay-1

#53 practica7
  practices/davo1956/practica07/practica07.py
Labels: delay-2
